apiVersion: v1
kind: ConfigMap
metadata:
  name: coubee-be-notification-config
data:
  application-stg.yml: |
    server:
      port: 8080

    spring:
      kafka:
        bootstrap-servers: kafka-service:9092